import React from "react";
import "./App.css";
import TextField from "@material-ui/core/TextField";
import Autocomplete from "@material-ui/lab/Autocomplete";
import Button from "@material-ui/core/Button";

export default function ControllableStates() {
  const [value, setValue] = React.useState(options[0]);
  const [value1, setValue1] = React.useState(options[0]);
  const [source, setSource] = React.useState("");
  const [dest, setDest] = React.useState("");

  function getFormData(e) {
    console.warn(source);
    console.warn(dest);
    e.preventDefault();
  }

  return (
    <div className="App">
      <div className="rowc">
        <form onSubmit={getFormData}>
          <div className="source">
            <Autocomplete
              value={value}
              onChange={(event, newValue) => {
                setValue(newValue);
              }}
              source={source}
              onInputChange={(event, newSource) => {
                setSource(newSource);
              }}
              id="controllable-states-demo"
              options={options}
              style={{ width: 300 }}
              renderInput={(params) => (
                <TextField {...params} label="City" variant="outlined" />
              )}
            />
          </div>

          <div className="dest">
            <Autocomplete
              value={value1}
              onChange={(event, newValue1) => {
                setValue1(newValue1);
              }}
              dest={dest}
              onInputChange={(event, newDest) => {
                setDest(newDest);
              }}
              id="controllable-states-demo"
              options={options}
              style={{ width: 300 }}
              renderInput={(params) => (
                <TextField {...params} label="City" variant="outlined" />
              )}
            />
          </div>

          <div className="btn">
            <Button type="submit" variant="contained" color="primary">
              SEARCH
            </Button>
          </div>
        </form>
      </div>
    </div>
  );
}

const options = [
  "Aba",
  "Abak",
  "Abakaliki",
  "Abeokuta",
  "Abocho",
  "Abraka",
  "Abuja",
  "Adani",
  "Ado-Ekiti",
  "Ado-Odo",
  "Adoru",
  "Afikpo",
  "Agaie",
  "Agbabu",
  "Agbor",
  "Agenebode",
  "Ago-Are",
  "Agulu",
  "Ahoada",
  "Ajaokuta",
  "Ajasse Ipo",
  "Akankpa",
  "Ake-Eze",
  "Akko",
  "Aku",
  "Akure",
  "Akwanga",
  "Alapa",
  "Aliade",
  "Amagunze",
  "Amaigbo",
  "Amassoma",
  "Amper",
  "Anchau",
  "Anka",
  "Ankpa",
  "Apomu",
  "Aramoko-Ekiti",
  "Argungu",
  "Arochukwu",
  "Asaba",
  "Atani",
  "Auchi",
  "Auna",
  "Awgu",
  "Awka",
  "Azare",
  "Babana",
  "Babura",
  "Badagry",
  "Badeggi",
  "Bagudo",
  "Baissa",
  "Bakori",
  "Bama",
  "Bara",
  "Baro",
  "Batsari",
  "Bauchi",
  "Bebeji",
  "Beli",
  "Bena",
  "Bende",
  "Benin City",
  "Benisheikh",
  "Bida",
  "Billiri",
  "Bin Yauri",
  "Binji",
  "Birnin Kebbi",
  "Birnin Kudu",
  "Birniwa",
  "Biu",
  "Bode Saadu",
  "Boi",
  "Boju",
  "Bokani",
  "Bokkos",
  "Bomadi",
  "Bonny",
  "Bori",
  "Bornu Yassu",
  "Buga",
  "Bugana",
  "Buguma",
  "Bukuru",
  "Bununu",
  "Burumburum",
  "Burutu",
  "Calabar",
  "Chakwama",
  "Dabai",
  "Dadiya",
  "Dakingari",
  "Damasak",
  "Damaturu",
  "Dambatta",
  "Damboa",
  "Dan Gora",
  "Dan Sadau",
  "Dange",
  "Danja",
  "Dankalwa",
  "Dankama",
  "Dapchi",
  "Darazo",
  "Dass",
  "Daura",
  "Daura",
  "Deba",
  "Degema Hulk",
  "Dekina",
  "Dengi",
  "Dikwa",
  "Dindima",
  "Disina",
  "Doma",
  "Dukku",
  "Duku",
  "Dutse",
  "Dutsen Wai",
  "Dutsin-Ma",
  "Ebute Ikorodu",
  "Effium",
  "Efon-Alaaye",
  "Egbe",
  "Eha Amufu",
  "Ejigbo",
  "Ejirin",
  "Eket",
  "Ekpoma",
  "Elele",
  "Emure-Ekiti",
  "Enugu",
  "Enugu-Ezike",
  "Enugu-Ukwu",
  "Epe",
  "Esuk Oron",
  "Ete",
  "Etinan",
  "Ezza-Ohu",
  "Fiditi",
  "Funtua",
  "Gabarin",
  "Gagarawa",
  "Gakem",
  "Gamawa",
  "Gamboru",
  "Gandi",
  "Ganye",
  "Garko",
  "Gashua",
  "Gassol",
  "Gaya",
  "Gbongan",
  "Geidam",
  "Gembu",
  "Gombe",
  "Gombi",
  "Goniri",
  "Gora",
  "Gorgoram",
  "Goronyo",
  "Gujba",
  "Gulma",
  "Gumel",
  "Gummi",
  "Gusau",
  "Gwadabawa",
  "Gwandu",
  "Gwaram",
  "Gwaram",
  "Gwarzo",
  "Gwasoro",
  "Gwio Kura",
  "Gwoza",
  "Hadejia",
  "Hinna",
  "Holma",
  "Hunkuyi",
  "Ibadan",
  "Ibeto",
  "Ibi",
  "Icheu",
  "Idah",
  "Idanre",
  "Idiroko",
  "Ifaki",
  "Ifo",
  "Ifon",
  "Igabi",
  "Igarra",
  "Igbara-Odo",
  "Igbeti",
  "Igbo-Ora",
  "Igbo-Ukwu",
  "Igboho",
  "Igbor",
  "Igede-Ekiti",
  "Ihiala",
  "Iho",
  "Ijebu-Ife",
  "Ijebu-Igbo",
  "Ijebu-Jesa",
  "Ijebu-Ode",
  "Ijero-Ekiti",
  "Ikang",
  "Ikeja",
  "Ikem",
  "Ikere-Ekiti",
  "Ikire",
  "Ikirun",
  "Ikom",
  "Ikot Ekpene",
  "Ila Orangun",
  "Ilare",
  "Ilaro",
  "Ilesa",
  "Illela",
  "Illushi",
  "Ilobu",
  "Ilorin",
  "Imeko",
  "Inisa",
  "Iperu",
  "Ipoti",
  "Isanlu-Itedoijowa",
  "Isara",
  "Ise-Ekiti",
  "Isieke",
  "Itu",
  "Iwo",
  "Jalingo",
  "Jebba",
  "Jega",
  "Jibia",
  "Jikamshi",
  "Jimeta",
  "Jos",
  "Kabba",
  "Kachia",
  "Kaduna",
  "Kafanchan",
  "Kafarati",
  "Kafin Hausa",
  "Kagoro",
  "Kaiama",
  "Kajuru",
  "Kaltungo",
  "Kamba",
  "Kangiwa",
  "Kankara",
  "Kano",
  "Kari",
  "Katagum",
  "Katsina",
  "Katsina-Ala",
  "Kaura Namoda",
  "Kazaure",
  "Keffi",
  "Kende",
  "Kibiya",
  "Kisi",
  "Kiyawa",
  "Konduga",
  "Konkwesso",
  "Kontagora",
  "Koton-Karfe",
  "Kujama",
  "Kuje",
  "Kukawa",
  "Kumagunnam",
  "Kumo",
  "Kura",
  "Kusheriki",
  "Kuta",
  "Kwale",
  "Kwali",
  "Kwatarkwashi",
  "Kwolla",
  "Lafia",
  "Lafiagi",
  "Lagos",
  "Lajere",
  "Lalupon",
  "Lame",
  "Langtang",
  "Lapai",
  "Lau",
  "Lekki",
  "Lere",
  "Lere",
  "Lokoja",
  "Machina",
  "Madagali",
  "Madala",
  "Madara",
  "Magumeri",
  "Mahuta",
  "Maiduguri",
  "Maiyama",
  "Makurdi",
  "Mallammaduri",
  "Malumfashi",
  "Mando",
  "Marte",
  "Maru",
  "Mashi",
  "Mayo-Belwa",
  "Mberubu",
  "Minna",
  "Miringa",
  "Misau",
  "Modakeke",
  "Mokwa",
  "Monguno",
  "Moriki",
  "Mubi",
  "Musawa",
  "Mutum Biyu",
  "Nafada",
  "Nasarawa",
  "New Shagunnu",
  "Ngala",
  "Ngurore",
  "Nguru",
  "Nkpor",
  "Nkwerre",
  "Nnewi",
  "Nsukka",
  "Numan",
  "Obiaruku",
  "Obolo-Eke (1)",
  "Obonoma",
  "Obubra",
  "Obudu",
  "Ochobo",
  "Ode",
  "Offa",
  "Ogaminana",
  "Ogoja",
  "Ogurugu",
  "Oguta",
  "Ogwashi-Uku",
  "Ohafia-Ifigh",
  "Oke Ila",
  "Oke Mesi",
  "Okeho",
  "Okene",
  "Okigwe",
  "Okrika",
  "Okuta",
  "Olupona",
  "Omoku",
  "Omu-Aran",
  "Omuo-Ekiti",
  "Ondo",
  "Onitsha",
  "Opi",
  "Ore",
  "Orerokpe",
  "Orita Eruwa",
  "Orlu",
  "Orodo",
  "Osogbo",
  "Otan Ayegbaju",
  "Otukpa",
  "Owerri",
  "Owo",
  "Owode",
  "Oyan",
  "Oyo",
  "Ozubulu",
  "Pankshin",
  "Panyam",
  "Patani",
  "Patigi",
  "Pindiga",
  "Port Harcourt",
  "Potiskum",
  "Rabah",
  "Rano",
  "Rijau",
  "Ringim",
  "Riti",
  "Ruma",
  "Runka",
  "Sade",
  "Saki",
  "Samamiya",
  "Saminaka",
  "Sapele",
  "Sauri",
  "Shaffa",
  "Shagamu",
  "Shanga",
  "Shani",
  "Shinkafi",
  "Siluko",
  "Soba",
  "Sofo-Birnin-Gwari",
  "Sokoto",
  "Suleja",
  "Suya",
  "Takai",
  "Takum",
  "Talata Mafara",
  "Tambuwal",
  "Tegina",
  "Tokombere",
  "Toungo",
  "Tsafe",
  "Twon-Brass",
  "Uba",
  "Ubiaja",
  "Udi",
  "Uga",
  "Ugbokpo",
  "Ugep",
  "Ughelli",
  "Ukata",
  "Umuahia",
  "Umunede",
  "Uromi",
  "Uruobo-Okija",
  "Uyo",
  "Vom",
  "Wagini",
  "Wamba",
  "Warri",
  "Wasagu",
  "Wawa",
  "Wudil",
  "Wukari",
  "Wurno",
  "Wuyo",
  "Yajiwa",
  "Yamrat",
  "Yanda Bayo",
  "Yandev",
  "Yashikira",
  "Yelwa",
  "Yenagoa",
  "Yola",
  "Yuli",
  "Zadawa",
  "Zaki Biam",
  "Zalanga",
  "Zango",
  "Zaria",
  "Zungeru",
  "Zuru",
];
